-- 2024-04-11
-- jspUser / mysql / jspdb
CREATE TABLE board(
bno INT NOT NULL AUTO_INCREMENT,
title VARCHAR(100) NOT NULL,
writer VARCHAR(50) NOT NULL,
content TEXT,
regdate DATETIME DEFAULT NOW(),
moddate DATETIME DEFAULT NOW(),
PRIMARY KEY(bno));

-- 2024-04-15
CREATE TABLE MEMBER(
id VARCHAR(100),
pwd VARCHAR(200) NOT NULL,
email VARCHAR(200) NOT NULL,
age INT DEFAULT 0,
phone VARCHAR(50),
regdate DATETIME DEFAULT NOW(),
lastlogin DATETIME DEFAULT NOW(),
PRIMARY KEY(id));

-- 2024-04-18
CREATE TABLE COMMENT(
cno INT AUTO_INCREMENT,
bno INT NOT NULL,
writer VARCHAR(100) DEFAULT "unknown",
content VARCHAR(1000) NOT NULL,
regdate DATETIME DEFAULT NOW(),
PRIMARY KEY(cno));

-- 2024-04-22
ALTER TABLE board ADD imageFile VARCHAR(100);
ALTER TABLE board ADD readCount INT DEFAULT 0;
